"""something

Revision ID: 0a87125155fb
Revises: 
Create Date: 2025-03-11 00:41:24.864451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a87125155fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_orderproduct_variations', schema=None) as batch_op:
        batch_op.drop_index('orders_orderproduct_vari_orderproduct_id_variatio_8c028ee7_uniq')

    op.drop_table('orders_orderproduct_variations')
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.drop_index('auth_permission_content_type_id_codename_01ab375a_uniq')

    op.drop_table('auth_permission')
    with op.batch_alter_table('accounts_account', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('accounts_account')
    op.drop_table('orders_order')
    op.drop_table('django_admin_log')
    with op.batch_alter_table('django_content_type', schema=None) as batch_op:
        batch_op.drop_index('django_content_type_app_label_model_76bd3d3b_uniq')

    op.drop_table('django_content_type')
    op.drop_table('store_product')
    op.drop_table('carts_cart')
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.drop_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq')

    op.drop_table('auth_group_permissions')
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('auth_group')
    with op.batch_alter_table('category_category', schema=None) as batch_op:
        batch_op.drop_index('category_name')
        batch_op.drop_index('slug')

    op.drop_table('category_category')
    op.drop_table('store_reviewrating')
    op.drop_table('orders_orderproduct')
    op.drop_table('carts_cartitem')
    op.drop_table('orders_payment')
    with op.batch_alter_table('carts_cartitem_variations', schema=None) as batch_op:
        batch_op.drop_index('carts_cartitem_variations_cartitem_id_variation_id_5f8efaf5_uniq')

    op.drop_table('carts_cartitem_variations')
    op.drop_table('store_variation')
    op.drop_table('django_migrations')
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.drop_index('django_session_expire_date_a5c62663')

    op.drop_table('django_session')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    op.create_table('django_session',
    sa.Column('session_key', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('expire_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.create_index('django_session_expire_date_a5c62663', ['expire_date'], unique=False)

    op.create_table('django_migrations',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('app', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('applied', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('store_variation',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('variation_category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('variation_value', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['store_product.id'], name='store_variation_product_id_e4f08cbc_fk_store_product_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('carts_cartitem_variations',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cartitem_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('variation_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cartitem_id'], ['carts_cartitem.id'], name='carts_cartitem_varia_cartitem_id_8be23372_fk_carts_car'),
    sa.ForeignKeyConstraint(['variation_id'], ['store_variation.id'], name='carts_cartitem_varia_variation_id_ef9f9ee3_fk_store_var'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('carts_cartitem_variations', schema=None) as batch_op:
        batch_op.create_index('carts_cartitem_variations_cartitem_id_variation_id_5f8efaf5_uniq', ['cartitem_id', 'variation_id'], unique=True)

    op.create_table('orders_payment',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('payment_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('payment_method', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('amount_paid', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_account.id'], name='orders_payment_user_id_cfa9f321_fk_accounts_account_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('carts_cartitem',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('cart_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts_cart.id'], name='carts_cartitem_cart_id_9cb0a756_fk_carts_cart_id'),
    sa.ForeignKeyConstraint(['product_id'], ['store_product.id'], name='carts_cartitem_product_id_acd010e4_fk_store_product_id'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_account.id'], name='carts_cartitem_user_id_4d21e0d9_fk_accounts_account_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orders_orderproduct',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_price', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('ordered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('order_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('payment_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders_order.id'], name='orders_orderproduct_order_id_5022a3e2_fk_orders_order_id'),
    sa.ForeignKeyConstraint(['payment_id'], ['orders_payment.id'], name='orders_orderproduct_payment_id_492ed997_fk_orders_payment_id'),
    sa.ForeignKeyConstraint(['product_id'], ['store_product.id'], name='orders_orderproduct_product_id_4d6ac024_fk_store_product_id'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_account.id'], name='orders_orderproduct_user_id_1e7a7ab7_fk_accounts_account_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('store_reviewrating',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('review', mysql.LONGTEXT(), nullable=False),
    sa.Column('rating', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['store_product.id'], name='store_reviewrating_product_id_2e1974d6_fk_store_product_id'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_account.id'], name='store_reviewrating_user_id_da0ed849_fk_accounts_account_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('category_category',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('category_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('category_category', schema=None) as batch_op:
        batch_op.create_index('slug', ['slug'], unique=True)
        batch_op.create_index('category_name', ['category_name'], unique=True)

    op.create_table('auth_group',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('auth_group_permissions',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.create_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq', ['group_id', 'permission_id'], unique=True)

    op.create_table('carts_cart',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cart_id', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('date_added', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('store_product',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('images', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('modified_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('category_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category_category.id'], name='store_product_category_id_574bae65_fk_category_category_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('django_content_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_content_type', schema=None) as batch_op:
        batch_op.create_index('django_content_type_app_label_model_76bd3d3b_uniq', ['app_label', 'model'], unique=True)

    op.create_table('django_admin_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('object_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('object_repr', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('action_flag', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('change_message', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`action_flag` >= 0)', name='django_admin_log_chk_1'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_account.id'], name='django_admin_log_user_id_c564eba6_fk_accounts_account_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orders_order',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address_line_1', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address_line_2', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('order_total', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('tax', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('is_ordered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('payment_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['orders_payment.id'], name='orders_order_payment_id_46928ccc_fk_orders_payment_id'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_account.id'], name='orders_order_user_id_e9b59eb1_fk_accounts_account_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('accounts_account',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('date_joined', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('last_login', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_superadmin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('address_line_1', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address_line_2', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('otp', mysql.VARCHAR(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('accounts_account', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('auth_permission',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.create_index('auth_permission_content_type_id_codename_01ab375a_uniq', ['content_type_id', 'codename'], unique=True)

    op.create_table('orders_orderproduct_variations',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('orderproduct_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('variation_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['orderproduct_id'], ['orders_orderproduct.id'], name='orders_orderproduct__orderproduct_id_0f116a3b_fk_orders_or'),
    sa.ForeignKeyConstraint(['variation_id'], ['store_variation.id'], name='orders_orderproduct__variation_id_5dfd0e51_fk_store_var'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('orders_orderproduct_variations', schema=None) as batch_op:
        batch_op.create_index('orders_orderproduct_vari_orderproduct_id_variatio_8c028ee7_uniq', ['orderproduct_id', 'variation_id'], unique=True)

    # ### end Alembic commands ###
